apiVersion: apps/v1
kind: Deployment
metadata:
  name: allowance
  labels:
    app: allowance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: allowance
  template:
    metadata:
      labels:
        app: allowance
    spec:
      containers:
        - name: allowance
          image: "username/allowance:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
