name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./request/pom.xml
          mvn clean package -f ./allowance/pom.xml
          mvn clean package -f ./customermanagement/pom.xml
          mvn clean package -f ./allocationmanagement/pom.xml
          mvn clean package -f ./customercenter/pom.xml

      - name: Docker Build and push for Request
        uses: docker/build-push-action@v4
        with:
          context: ./request
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/request:latest
            ghcr.io/${{ github.repository }}/request:${{ github.ref_name }}
            
      - name: Docker Build and push for Allowance
        uses: docker/build-push-action@v4
        with:
          context: ./allowance
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/allowance:latest
            ghcr.io/${{ github.repository }}/allowance:${{ github.ref_name }}
            
      - name: Docker Build and push for Customermanagement
        uses: docker/build-push-action@v4
        with:
          context: ./customermanagement
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/customermanagement:latest
            ghcr.io/${{ github.repository }}/customermanagement:${{ github.ref_name }}
            
      - name: Docker Build and push for Allocationmanagement
        uses: docker/build-push-action@v4
        with:
          context: ./allocationmanagement
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/allocationmanagement:latest
            ghcr.io/${{ github.repository }}/allocationmanagement:${{ github.ref_name }}
            
      - name: Docker Build and push for Customercenter
        uses: docker/build-push-action@v4
        with:
          context: ./customercenter
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/customercenter:latest
            ghcr.io/${{ github.repository }}/customercenter:${{ github.ref_name }}
            
