server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: request
          uri: http://localhost:8082
          predicates:
            - Path=/allocations/**, 
        - id: allowance
          uri: http://localhost:8083
          predicates:
            - Path=/allowanceChecks/**, 
        - id: customermanagement
          uri: http://localhost:8084
          predicates:
            - Path=, 
        - id: allocationmanagement
          uri: http://localhost:8085
          predicates:
            - Path=/allocationManagements/**, 
        - id: customercenter
          uri: http://localhost:8086
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: request
          uri: http://request:8080
          predicates:
            - Path=/allocations/**, 
        - id: allowance
          uri: http://allowance:8080
          predicates:
            - Path=/allowanceChecks/**, 
        - id: customermanagement
          uri: http://customermanagement:8080
          predicates:
            - Path=, 
        - id: allocationmanagement
          uri: http://allocationmanagement:8080
          predicates:
            - Path=/allocationManagements/**, 
        - id: customercenter
          uri: http://customercenter:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
