---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: request
  labels:
    app: request
spec:
  replicas: 1
  selector:
    matchLabels:
      app: request
  template:
    metadata:
      labels:
        app: request
    spec:
      containers:
        - name: request
          image: username/request:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: allowance
  labels:
    app: allowance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: allowance
  template:
    metadata:
      labels:
        app: allowance
    spec:
      containers:
        - name: allowance
          image: username/allowance:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: customermanagement
  labels:
    app: customermanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customermanagement
  template:
    metadata:
      labels:
        app: customermanagement
    spec:
      containers:
        - name: customermanagement
          image: username/customermanagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: allocationmanagement
  labels:
    app: allocationmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: allocationmanagement
  template:
    metadata:
      labels:
        app: allocationmanagement
    spec:
      containers:
        - name: allocationmanagement
          image: username/allocationmanagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: request
  labels:
    app: request
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: request


---


apiVersion: v1
kind: Service
metadata:
  name: allowance
  labels:
    app: allowance
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: allowance


---


apiVersion: v1
kind: Service
metadata:
  name: customermanagement
  labels:
    app: customermanagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: customermanagement


---


apiVersion: v1
kind: Service
metadata:
  name: allocationmanagement
  labels:
    app: allocationmanagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: allocationmanagement

