apiVersion: v1
kind: Service
metadata:
  name: allocationmanagement
  labels:
    app: allocationmanagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: allocationmanagement